[programs.devnet]
bird_vs_drone = "2XdJLmGEcJUhF61tYNj9xL9frsao675akcXfGCBQoa9H"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/chompchomp/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"